services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
    - "80:80"
  mysqldb:
    image: mysql:5.7
    restart: always
    volumes:
    - ./mysql_data:/var/lib/mysql